Docker: Use opensearch 2
OpenSearch 3 doesn't support the same index types as AWS Serverless opensearch does:

```
opensearchpy.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Failed to parse mapping [_doc]: nmslib engine is deprecated in OpenSearch  and cannot be used for new index creation in OpenSearch from  3.0.0.')
```