Update PyArrow to ^18.0.0 (#278)
## Problem

Attemping to install VSB on macOS 15.11 and Python 3.13 fails with the
following error:

```
- Installing pyzmq (26.0.3): Failed
...
    CC       crypto_aead/aes256gcm/armcrypto/libarmcrypto_la-aead_aes256gcm_armcrypto.lo
  In file included from crypto_aead/aes256gcm/armcrypto/aead_aes256gcm_armcrypto.c:35:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include/arm_neon.h:62828:32: error: always_inline function 'vget_high_p64' requires target feature 'crypto', but would be inlined into function 'vmull_high_p64' that is compiled without support for 'crypto'
   62828 |   __ret = vmull_p64((poly64_t)(vget_high_p64(__p0)), (poly64_t)(vget_high_p64(__p1)));
         |                                ^
  make[3]: *** [crypto_aead/aes256gcm/armcrypto/libarmcrypto_la-aead_aes256gcm_armcrypto.lo] Error 1
```

This appears to be caused by the attempt to build pyzmq's libsodium
dependancy from source (no pre-built wheel). A `poetry update` to update
deps addresses this issue, however that runs into a problem installing
PyArrow:

```
  CMake Error at CMakeLists.txt:266 (find_package):
    By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Arrow", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "Arrow" with any of
    the following names:
  
      ArrowConfig.cmake
      arrow-config.cmake
  
    Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
    "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
    provides a separate development package or SDK, be sure it has been
    installed.
```

Fix _that_ issue (and subsequently Python 3.13 support on macOS) by
updating PyArrow to the next major version (18) which has pre-built
wheels for macOS 15.1.1.

Fixes #276.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)