Ensure num_users is always a non-zero value
locust's --users argument does not have a default value (defaults to
None). This is problematic when --processes is specified as locust
doesn't set it to 1 - see start_automatic_run():

        if not options.worker:
            # apply headless mode defaults
            if options.num_users is None:
                options.num_users = 1

As such, when we attempt to later use num_users when setting up the
parquet workload, we attempt to comapre int and None and throw:

    Traceback (most recent call last):
      File /Users/dave/repos/pinecone-io/VSB/vsb/users.py, line 55, in do_load
	self.load_iter = self.workload.get_record_batch_iter(
			 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File /Users/dave/repos/pinecone-io/VSB/vsb/workloads/parquet_workload/parquet_workload.py, line 40, in get_record_batch_iter
	batch_iter = self.dataset.get_batch_iterator(num_users, user_id, 200)
		     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File /Users/dave/repos/pinecone-io/VSB/vsb/workloads/dataset.py, line 112, in get_batch_iterator
	assert chunk_id < num_chunks
	       ^^^^^^^^^^^^^^^^^^^^^
    TypeError: '<' not supported between instances of 'int' and 'NoneType'

Address this by defaulting to 1 ourselves in PopulateUser.